DROP TABLE IF EXISTS item;

DROP TABLE IF EXISTS user_share_it;

CREATE TABLE IF NOT EXISTS user_share_it (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR UNIQUE NOT NULL,
    user_name VARCHAR        NOT NULL,

    CONSTRAINT email_symbol CHECK (email LIKE '%@%'),
    CONSTRAINT login_without_space CHECK (user_name NOT LIKE ' ' AND user_name NOT LIKE '')
);


CREATE TABLE IF NOT EXISTS item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR NOT NULL,
    description  VARCHAR NOT NULL,
    owner_id     BIGINT  NOT NULL REFERENCES user_share_it (id) ON DELETE CASCADE NOT NULL,
    is_available BOOLEAN NOT NULL,

    CONSTRAINT title_without_space CHECK (title NOT LIKE ' ' AND title NOT LIKE ''),
    CONSTRAINT description_space CHECK (description NOT LIKE ' ' AND description NOT LIKE '')
);