DROP TABLE IF EXISTS item_request;

DROP TABLE IF EXISTS comment;

DROP TABLE IF EXISTS booking_order;

DROP TABLE IF EXISTS item;

DROP TABLE IF EXISTS user_share_it;

CREATE TABLE IF NOT EXISTS user_share_it (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(400) UNIQUE NOT NULL,
    user_name VARCHAR(50)         NOT NULL,

    CONSTRAINT email_symbol CHECK (email LIKE '%@%'),
    CONSTRAINT login_without_space CHECK (user_name NOT LIKE ' ' AND user_name NOT LIKE '')
);


CREATE TABLE IF NOT EXISTS item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(100)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    owner_id     BIGINT        NOT NULL REFERENCES user_share_it (id) ON DELETE CASCADE,
    is_available BOOLEAN       NOT NULL,

    CONSTRAINT title_without_space CHECK (title NOT LIKE ' ' AND title NOT LIKE ''),
    CONSTRAINT description_space CHECK (description NOT LIKE ' ' AND description NOT LIKE '')
);


CREATE TABLE IF NOT EXISTS booking_order (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES user_share_it (id) ON DELETE CASCADE,
    item_id    BIGINT    NOT NULL REFERENCES item (id) ON DELETE CASCADE,
    status     INTEGER,
    start_time TIMESTAMP NOT NULL,
    end_time   TIMESTAMP NOT NULL,

    CONSTRAINT booking_time CHECK ( start_time < end_time )
);


CREATE TABLE IF NOT EXISTS comment (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT    NOT NULL REFERENCES user_share_it (id) ON DELETE CASCADE,
    item_id BIGINT    NOT NULL REFERENCES item (id) ON DELETE CASCADE,
    note    TEXT      NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT message_not_empty CHECK ( note NOT LIKE ' ' AND note NOT LIKE '' )
);


CREATE TABLE IF NOT EXISTS item_request (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT      NOT NULL,
    author_id   BIGINT    NOT NULL REFERENCES user_share_it (id) ON DELETE CASCADE,
    created     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT description_not_empty CHECK ( description NOT LIKE ' ' AND description NOT LIKE '' )
);