DROP
ALL OBJECTS;

CREATE TABLE IF NOT EXISTS user_share_it (
    id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    name  VARCHAR        NOT NULL,

    CONSTRAINT email_symbol CHECK (email like '%@%'),
    CONSTRAINT login_without_space CHECK (name not like '% %' AND name <> '')
);


CREATE TABLE IF NOT EXISTS item (
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title        VARCHAR NOT NULL,
    description  VARCHAR NOT NULL,
    owner_id     INTEGER NOT NULL REFERENCES user_share_it (id) ON DELETE CASCADE,
    is_available BOOLEAN NOT NULL,

    CONSTRAINT title_without_space CHECK (title not like '% %' AND title <> ''),
    CONSTRAINT description_space CHECK (description not like '% %' AND description <> '')
)